### ISSUE TITLE
Draft preview button

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-frontend#10]

**Comment by thomasstjerne** [comment]
Not relevant ? as draft will update immediately after attachment of a sector

**Comment by mdoering** [comment]
It will update, but some of those updates might take minutes or even half an hour to finish. How do we communicate syncs in progress and how is the UI updated? Is simple polling really enough?

I would definitely prominently show a colored in sync/syncing badge when viewing the draft
