### ISSUE TITLE
Add all name search filters

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#100]
The name usage search offers more parameters then the UI currently offers:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/search/NameSearchParameter.java#L12

Filters for ids are not really needed, but we should consider to expose the following at least in an advanced mode that is hidden by default:

 - nom status
 - type
 - field

**Comment by thomasstjerne** [comment]
Do we have facets for those or should they be retrieved from /vocab ?
And how do I use facets, this seems not to work: http://api.col.plus/dataset/2052/name/search?limit=50&offset=0&facet=rank

**Comment by mdoering** [comment]
All NameSearchParameter filters should be available as facets

**Comment by mdoering** [comment]
Hm, the search URL you have given is correct. This seems like a bug to me.
Actually the message 
```
{
  "code": 400,
  "message": "Collection is empty"
}
```

feels like a misconfiguration. 
@ayco-at-naturalis can you please help out?

**Comment by thomasstjerne** [comment]
I think the names index ignores nametype and namefield params

e.g.: http://api.col.plus/dataset/1010/name/search?limit=50&nametype=otu&offset=0

**Comment by mdoering** [comment]
Its just called "type": http://api.col.plus/dataset/1010/name/search?limit=50&type=otu&offset=0
Should we change that to always make sure params correspond to http://api.col.plus/vocab ?

**Comment by mdoering** [comment]
The property on Name is just called type, thats why its like that

**Comment by thomasstjerne** [comment]
> Should we change that to always make sure params correspond to http://api.col.plus/vocab ?

Should not be neccesary - as long as I know which params it corresponds to.
But if they all can be retrieved from facets the problem is solved.

**Comment by mdoering** [comment]
facet API fixed: http://api.col.plus/dataset/2052/name/search?q=Parasteatoda&limit=50&offset=0&facet=rank
