### ISSUE TITLE
Change the title to the issue name for the issues pages

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#103]
The issues pages would be clearer and easier to work with if the title changes to match whichever issue is selected. With multiple tabs open it gets confusing. 

For example, this [issue page](http://test.col.plus/dataset/1140/names?issue=parent%20id%20invalid) would be clearer with the title "Parent ID Invalid" instead of "World Ferns: Checklist of Ferns and Lycophytes of the World."

**Comment by gdower** [comment]
On a related note, changing the meta page title from "React App" to something more descriptive would also be helpful.

**Comment by yroskov** [comment]
Datasource name ("World Ferns: Checklist of...") in the title of the page is also important. Please just add issue title (Parent ID Invalid) to the page title.

**Comment by mdoering** [comment]
I agree the filter on the top right are not at the focus of attention on that page.
But I'm not sure if the title is the right place for it. What if you select multiple issues? and a rank or more? and a status or other filters to come (see #100)? I think we need a more generic and expandable way to show selected and offer available filters with counts (see #99)

**Comment by mdoering** [comment]
totally agree with changing "React App" to sth more sensible. "CoL Clearinghouse" maybe?

**Comment by thomasstjerne** [comment]
Putting issues, ranks and other search criteria in the title is not feasible. 

For now, I have changed the default title to CoL+ and when in scope of a dataset, the dataset title
