### ISSUE TITLE
Manage sectors and colsources

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#108]
With [sectors being linked directly to a dataset](https://github.com/Sp2000/colplus-backend/issues/243) colsources can and should be managed entirely separate from sector mappings. This allows us to reuse sectors for catalogues without a colsource (e.g. pCat). 

Suggest to have a new sectors section under assembly that lists all sectors with filtering by dataset, colsource or rank? And the option to bulk assign a colsource to multiple sectors?

**Comment by mdoering** [comment]
relates to https://github.com/Sp2000/colplus-backend/issues/244

**Comment by mdoering** [comment]
We also need to list sectors (and also ultimately decisions) which have broken references to taxa in source datasets. These need to be fixed by the user or be updated semiautomatically with a suggested replacement taxonID.

The API allows to retrieve such broken sectors with optional filter params:
/sector/broken?datasetKey=X&sourceKey=Y

**Comment by thomasstjerne** [comment]
Closing in favour of #148
