### ISSUE TITLE
Taxon fossil/extinct flags not shown

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#126]
Taxon page should show 2 boolean flags, ideally combined in a single row as "recent/fossil":

```
 "fossil": true,
 "recent": false,
```

https://www.col.plus/dataset/2044/taxon/Dendroxena_sexcarinata_pliocaenica
https://api.col.plus/dataset/2044/taxon/Dendroxena_sexcarinata_pliocaenica

**Comment by thomasstjerne** [comment]
A matter of updating www:
https://dev.col.plus/dataset/2044/taxon/Dendroxena_sexcarinata_pliocaenica
