### ISSUE TITLE
How to get to taxon page from name?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#127]
When Im on a names page its a dead end and I cannot see its name usages (synonyms or taxon). Link to name usages, e.g via name search using the `NAME_ID` parameter
https://dev.col.plus/dataset/1604/name/Lathrobium_Lathrobium_contentum

**Comment by thomasstjerne** [comment]
Given a name, how do I retrieve the taxon (or taxa) that has a usage of that name? i.e. get taxa by nameId. I tried https://api-dev.col.plus/dataset/1700/name/1001/usage(s) with no luck.

**Comment by thomasstjerne** [comment]
depends on https://github.com/Sp2000/colplus-backend/issues/550
