### ISSUE TITLE
Order verbatim terms consistently

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-frontend#129]

**Comment by mdoering** [comment]
Is it useful to have a list of all known terms in the vocab service, arranged by namespace and ordering within? That should be fairly straight forward.

Or should we rather have a term order specific for each rowType/class it occurs under?

**Comment by mdoering** [comment]
I am exposing all terms ordered in vocab API like this:
http://localhost:8080/vocab/terms
Or just a single term namespace:
http://localhost:8080/vocab/terms?prefix=dc

**Comment by gdower** [comment]
@mdoering, if you can order the verbatim data consistently and in particular order the verbatim classification hierarchy correctly that would be extremely helpful.

**Comment by mdoering** [comment]
@gdower, @thomasstjerne  I think the idea was to sort it client side according to the terms oder exposed here: http://api.col.plus/vocab/terms

The API returns an object with terms as keys which is not guaranteed to be sorted in the same way:
https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

Unless we come up with an array based return object it would be best to sort this client side - which should be fairly simple for the few records we actually show
