### ISSUE TITLE
Diff tool - Unlikely name matchs

### ISSUE THREAD

**Issue by camiplata** [Sp2000/colplus-frontend#1332]
Some example of incorrect name matche of two sources:

1. On the first blue box   Hesionoidea was match to  Iphionidae, although both datasets had the name  Iphionidae
2. On the second blue box, two completely different names are match although they do not share most  of its characters, and there was a better match for  Sigalionidae
<img width="697" alt="Captura de pantalla 2023-12-01 a la(s) 10 53 48 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/f458f8b3-e857-4bd7-9070-a3e67ed8ceef">

[Link to the diff tool](https://www.checklistbank.org/tools/diff-viewer?dataset=279792&dataset2=2144&root=10&root2=914225)

3. The following image shows  two unlikely matchs and
4. A name that had a better match but it was pair with a less likely name

<img width="776" alt="Captura de pantalla 2023-12-01 a la(s) 11 07 34 a m  3" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/5cf0b6d1-c56a-4fd1-a19a-c3a8f35069f7">

 [Link to the diff tool](https://www.checklistbank.org/tools/diff-viewer?dataset=279792&dataset2=2011&root=3&root2=urn%3Alsid%3Amarinespecies.org%3Ataxname%3A882)

**Comment by mdoering** [comment]
These are not matches - they simply show where things have changed. 
It is not always easy to understand these diffs. Don't put any taxonomic meaning into them, they simply show where files differ. It quite often happens that a name was removed and another name added and these 2 are shown as "pairs" when really there is no pairing - they just happen to be in the same place when sorted alphabetically!

**Comment by mdoering** [comment]
Also this is a based on the regular unix diff software and we do not have any influence on its performance

**Comment by camiplata** [comment]
I do think there is room for improvement of the tool and the documentation about it. 

 If changes  are shown as pairs like this:
<img width="720" alt="Captura de pantalla 2023-12-01 a la(s) 1 35 52 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/fd16beee-3798-4bd9-bc98-910fe09ec4ab">

It intermediately creates the idea on the user that that's how the diff is read for all names. If there is not a pairing the name could be shown alone like this as the tool already does:

<img width="680" alt="Captura de pantalla 2023-12-01 a la(s) 1 37 58 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/649aa8d4-cd76-4f32-9aac-f6d2432d2d3d">

On the other hand if the tool shows differences between datasets I do expect it to retrieve better pairs for example

 here with Iphionidae
<img width="711" alt="Captura de pantalla 2023-12-01 a la(s) 1 39 32 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/dd18fd8e-acd3-4f42-a0ff-4e5fbd6b92da">

 and here with Annelida
<img width="761" alt="Captura de pantalla 2023-12-01 a la(s) 1 39 42 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/c06334d9-987c-429e-b3b1-4e4601177e77">
 should had been paired

Probably this is not a higher priority issue, but if this a tool we are going to offer to the wider public we would need  to make it better enventually, and questions/issues like the one I'm raising will eventually arrive again from users.

**Comment by mdoering** [comment]
Agree it is unfortunate, but there is no way to improve these problems. It can only be done by better documenting what it does
