### ISSUE TITLE
Failed sector syncs

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#135]
If a sector sync fails we need a way to show what has happened

**Comment by mdoering** [comment]
Suggest to use a similar approach as for dataset imports, i.e. we show a simple error message in the sync state and then link to Kibana via a new sector field that takes the sectorKey.

Also a new attempt field should be added to the logs both for dataset & sector imports so we can reliably link to exactly one import

**Comment by thomasstjerne** [comment]
Is there an api to retrieve this already?

**Comment by mdoering** [comment]
not yet. But links to logs should now be in kibana with the deploy just now

**Comment by mdoering** [comment]
Kibana now has `sector` and `attempt`  to link to sync logs

**Comment by mdoering** [comment]
attempt is also populated now for dataset imports

**Comment by mdoering** [comment]
https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:sector,negate:!f,type:phrase,value:'1055'),query:(match:(sector:(query:'1055',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'0'),query:(match:(attempt:(query:'0',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))

**Comment by mdoering** [comment]
New API now for sector syncs similar to dataset imports:

State of the continuous assembly with a current `running` object and a queue of upcoming ones:
GET http://api-dev.col.plus/assembly/3/sync

List of running (includes queued) or completed syncs:
GET http://api-dev.col.plus/assembly/3/sync/sector?sectorKey=X&running=true&limit=10

Schedule new sector sync
POST [http://api-dev.col.plus/assembly/3/sync/sector/{key}](http://api-dev.col.plus/assembly/3/sync/sector/%7Bkey%7D)

Cancel a sector sync
DELETE [http://api-dev.col.plus/assembly/3/sync/sector/{key}](http://api-dev.col.plus/assembly/3/sync/sector/%7Bkey%7D)

Retrieve one sync attempt
GET [http://api-dev.col.plus/assembly/sync/3/sector/{key}/{attempt}](http://api-dev.col.plus/assembly/sync/3/sector/%7Bkey%7D/%7Battempt%7D)

**Comment by mdoering** [comment]
@thomasstjerne if you need sth else please let me know

**Comment by thomasstjerne** [comment]
New routes are
catKey=3 for draft catalogue

```
# quick polling of assembly state
GET /assembly/{catKey}

# page through past syncs, query params optional
GET /assembly/{catKey}/sync?sectorKey=1&running=true&state=FAILED

# queue new sector sync
POST /assembly/{catKey}/sync
body: ```{sectorKey=1}```

# cancel sector sync
DELETE /assembly/{catKey}/sync/{sectorKey}

# get sector sync by attempt
GET /assembly/{catKey}/sync/{sectorKey}/{attempt}

# get sector sync diff. Defaults to diff between last 2 syncs, otherwise optional query param
GET /assembly/{catKey}/sync/{sectorKey}/diff?attempts=3..7

# delete entire sector and all its data
DELETE /assembly/{catKey}/sector/{key}

```
