### ISSUE TITLE
Upload form HTTP post error

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#138]
On dev.col.plus the upload form throws an HTTP post error when trying to manually add a zip file:

![HTTP post error](https://i.gyazo.com/071f2c2cb9234d4cc12926d85d7b900e.png)

**Comment by thomasstjerne** [comment]
@mdoering was wiping dev, right now. Can you try again when its back up?

**Comment by mdoering** [comment]
we did and its still the same

**Comment by mdoering** [comment]
Looks like the URL is using a null var: https://api-dev.col.plus/importer/undefined

**Comment by gdower** [comment]
The post error is back on www.col.plus with a 502 bad gateway error to the request URL: https://api.col.plus/importer/undefined. I was trying to upload a zip archive for [2044](https://www.col.plus/dataset/2044/meta).

**Comment by mdoering** [comment]
confirm its posting to an undefined route

**Comment by mdoering** [comment]
@thomasstjerne can we try to fix this asap? It stop Geoff and me from testing

**Comment by mdoering** [comment]
similar also importing external datasets fails cause no datasetKey is given
<img width="326" alt="screenshot 2019-03-01 at 12 58 26" src="https://user-images.githubusercontent.com/327505/53636822-cc425f80-3c21-11e9-9cf3-e33d8fad5f3a.png">

**Comment by mdoering** [comment]
For uploading files it should be:
POST: /importer/{datasetKey}

For queuing an external import:
POST: /importer/queue
with a JSON request body of:
```
{"datasetKey":1234, 
 "priority": false,
 "force": true
}
```

See also #75
