### ISSUE TITLE
Upload archive improvements

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#139]
1) If possible, it would be great if zip files could be uploaded from the new dataset form after asking for the data format:

![New dataset form](https://i.gyazo.com/0826f4d10606ccccf178abe4f6e920f8.png)

2) Also, on the meta data page the upload archive form should be displayed at the top of the page and not hidden under the edit section. Being able to quickly update zip archives is going to be important for debugging problems with manually registered datasets.

**Comment by thomasstjerne** [comment]
1) will not be possible. Have to create the dataset before being able to post an archive to it
2) Should be possible

**Comment by gdower** [comment]
If you can send the user to the meta data page after the dataset is registered and implement #2 above, I think it'll be clearer where to upload the dataset.
