### ISSUE TITLE
Dataset import button not showing when never imported before

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#142]
The import button for external datasets (and likely same for upload) is not showing under the imports menu if there hasnt been any import yet

**Comment by thomasstjerne** [comment]
Are you logged in?
I see it: 
![import_btn](https://user-images.githubusercontent.com/1666484/53232713-ff1dae00-368b-11e9-8a53-188795b55485.png)

**Comment by mdoering** [comment]
I think you are right, I see it now too 👍
