### ISSUE TITLE
List all synonyms in the same main Taxon block

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#143]
Homotypic and hetero-/unknown synonyms are shown as distinct main categories with the later just labelled "Synonyms". Homotypic ones are synonyms too and I think it would be cleaner to show all synonyms under one "Synonyms" heading, but marking homotypic ones somehow. Maybe using the indented headings we also use for name rels and the classification?

https://dev.col.plus/dataset/2045/taxon/183

<img width="1635" alt="screenshot 2019-02-22 at 11 29 29" src="https://user-images.githubusercontent.com/327505/53236803-71df5700-3695-11e9-92da-4d0e068d8ff3.png">

**Comment by thomasstjerne** [comment]
Could we then change the API response to only return one array of synonyms and mark homotypic: true/false Instead of returning an object with homotypic and heterotypic arrays?

**Comment by mdoering** [comment]
Well, the point of the homotypic groupings was to render synonyms in homotypic groups like here:

![cdm_agoseris_apargioides_synonymy](https://user-images.githubusercontent.com/327505/53343531-dd812880-3910-11e9-980e-889993eadb53.png)

We do not have much of such information available at this stage, but I would think if we have the means to show that, data will follow. @gdower had mobilised some nice data from StaphBase already

**Comment by mdoering** [comment]
So they are lists of homotypic lists

**Comment by thomasstjerne** [comment]
Could still make such lists, just by filtering on homotipic: true

**Comment by mdoering** [comment]
No, these are lists of lists. Each list groups all homotypic names. Having a flat list and a boolean flag does not allow to present them like above.

**Comment by thomasstjerne** [comment]
well, It is a matter of whether each synonym is individually marked as homotypic or if this information is only known from which list (homo/hetero) it was taken from.
i.e. 
homotypicSynonyms === allSynonyms.filter( s => !!s.homotypic)
heterotypicSynonyms === allSynonyms.filter( s => !s.homotypic)

But its easy to merge them client side, so no worries
