### ISSUE TITLE
Sector sync seems to erase entire dataset in tree

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#145]
when I have to family sectors from the same dataset (Cycads) and only sync one of them the genera already in the tree for the other one are removed from the tree. If I close and reopen the family they show, so its fine in the db

**Comment by thomasstjerne** [comment]
Indeed. It is reloading the parents children, and thereby pruning off all nephews.
Not sure if I can change it

**Comment by mdoering** [comment]
At least showing a closed node instead of an open & pruned one would be good. The way it is looks like the data got deleted
