### ISSUE TITLE
Plantae sector not attaching for Cycads

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#146]
When trying to attach kingdom Plantae in the [Cycads dataset](https://dev.col.plus/dataset/2045/meta) to the Biota superkingdom:

![sector attachment](https://i.gyazo.com/9e0f1797b420243835a79f2e9d3c5958.png)

the sector fails to attach with the following error

![error](https://i.gyazo.com/8a304e20ecf87f3b8fd3df89ca38944c.png)

**Comment by mdoering** [comment]
Its a bad request error, trying to create a duplicate sector with the same datasetKey and same subjectID. That is not allowed and the UI should probably present sth more meaningful, catching 400 responses.

**Comment by thomasstjerne** [comment]
The UI will now format the message and put it in a red box. (But it will still be the message sent from the API)
