### ISSUE TITLE
Show decisions in the assembly source tree

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#147]
requires the tree API to return a decisionKey or full Decision attached to a TreeNode

**Comment by mdoering** [comment]
Consider to show blocked taxa in the source tree with ~~strike through~~

**Comment by mdoering** [comment]
How should we handle synonyms? So far they are not part of the tree API, but we could add them I guess and set the correct status

**Comment by thomasstjerne** [comment]
I dont know if they are important in the assembly view, or if they will just add complexity?
Otherwise, they could be treated like children, adding synonym count to tree taxa, if > 0 indicates that synonyms could be fetched and shown in a popover or similar?

**Comment by mdoering** [comment]
Let's ask @yroskov about that first. Synonyms dont interact with setting up sectors, but they are relevant for duplicates and therefore general editorial decisions. But might be better dealt with in a flat workbench view

**Comment by yroskov** [comment]
Synonyms should not be a part of the tree. I do not need them in attaching sectors. 
Markus right, synonyms in workbench view (check for duplicates) help to identify possible overlaps in sectors and resolve them.
Above statements are true for a single management classifiction without synonyms in taxa above species. Synonymy in higher taxa is very much complicated issue which need to be discussed by experts in details: synonymy in nomenclatural sense (where the name uniquely associated with the type) VS synonymy in taxonomic sense (synonymy of sets/concepts).

**Comment by mdoering** [comment]
Deployed to dev: http://api-dev.col.plus/dataset/1203/tree/.ekQ9

**Comment by mdoering** [comment]
eh, backend is done, frontend awaiting
