### ISSUE TITLE
"n is undefined" on classification for Cycads dataset

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#149]
There is an "n is undefined" error on the classification tab for the [Cycads dataset](https://www.col.plus/dataset/2046/classification). It likely is caused by a problem with the dataset, because it doesn't happen for other datasets. I looked through the JSON requests and didn't see any obvious cause. It would be helpful to have a more descriptive error message.

**Comment by gdower** [comment]
The [latest version of the dataset from Markus' repo](https://www.col.plus/dataset/2047/classification) doesn't generate the error, but if it becomes a common error then improving the error message would be helpful. I'll reopen this issue if it happens again with another dataset.

**Comment by gdower** [comment]
I remembered what caused this bug and it would be useful to have a better error message, because I think it could easily happen again. The Taxon.tsv was missing, which generated the classification 'n is undefined' error.

**Comment by thomasstjerne** [comment]
Closing this as the code has been rewritten several times since the issue was opened. Please reopen if you encounter it again
