### ISSUE TITLE
Show merged sector on parent?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#160]
When you create a MERGE sector with multiple children they are all shown as root sectors. You cannot tell that they are all the same really. And if you show the source, it points to a higher rank.

<img width="1113" alt="screenshot 2019-03-01 at 13 53 34" src="https://user-images.githubusercontent.com/327505/53639533-c94b6d00-3c29-11e9-900a-79c591772ede.png">

I think its better to have a single sector shown on the actual target node, but maybe there are other ways of improving. For ATTACHed sectors its very fine like it is.

**Comment by thomasstjerne** [comment]
Superseeded by https://github.com/Sp2000/colplus-frontend/issues/298
