### ISSUE TITLE
Create admin page

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#164]
A simple admin page from where we can trigger various routines is needed. Reserved users with for admin rights only.

Initially just buttons that trigger the API:

- [x] update all logos async: `POST /admin/logo-update`
- [x] sync all sectors: `POST {"all": true} /assembly/3/sync`
- [x] export CoL draft to old portal synchroneously (might take long): `POST /assembly/3/exportAC`
- [x] recalculate sector counts: `POST /admin/sector-count-update`
- [ ] rematch all sectors, decisions & estimates `POST {"all":true} /admin/rematch`
- [x] rematch all broken sectors & decisions `POST: /admin/rematch-decisions`
- [ ] reindex all datasets: `POST {"all": true} /admin/reindex`

Maybe these dataset scoped admin commands could also go into the dataset menu somewhere. Or maybe an admin page under dataset? Otherwise we need a dataset lookup form in the global admin page:
- [x] rematch one dataset `POST {"datasetKey": 1234} /admin/rematch`
- [x] reindex one datasets: `POST {"datasetKey": 1234} /admin/reindex`

**Comment by thomasstjerne** [comment]
"reindex one dataset", do you mean trigger an import?

**Comment by mdoering** [comment]
No, reindex into Elastic Search - that is not yet exposed anywhere

**Comment by mdoering** [comment]
The rematch all API method from above does not exist.
Can we please change this to:

rematch all broken sector targets `POST: /sector//broken/rematch`

**Comment by mdoering** [comment]
and add a new button to trigger a restart of the backend.
Currently only avail for prod: https://builds.gbif.org/job/colplus-restart-prod/build?token=TOKEN_NAME

@thomasstjerne this needs a secret token to trigger the jenkins build programmatically, please get in touch with me directly for that.

**Comment by mdoering** [comment]
I think I would prefer a different layout with one button on its own "row" to increase readability and maybe a small info line on what this does

**Comment by mdoering** [comment]
@thomasstjerne the index and rematch one dataset API as given above does exist - would be great to allow an admin to trigger that. It actually would help me to debug the nasty [postgres tmp file bug](https://github.com/Sp2000/colplus-backend/issues/498).
