### ISSUE TITLE
Allow "replace" sector mappings

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#167]
When a classification exists it happens that one want to replace a taxon with one from the source. E.g. map the family _Asteraceae_ to the existing family _Asteraceae_ in the draft classification. Essentially this constitutes of 2 operations: 2) delete the existing Asteraceae taxon and 2) attaching the _Asteraceae_ to the higher order.

When ranks are the same the frontend should ask whether to perform a MERGE operation or a REPLACE - which under the hood first deletes the existing family and then ATTACHes the new root family

**Comment by thomasstjerne** [comment]
Needs fix of https://github.com/Sp2000/colplus-backend/issues/418
