### ISSUE TITLE
consider citeproc-js for rendering references

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#175]
https://citeproc-js.readthedocs.io/en/latest/

**Comment by thomasstjerne** [comment]
Good idea!

This would require the backend to return [CSL-JSON](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html) for the references

Example: https://api.zotero.org/groups/459003/items?format=csljson&limit=6&itemType=journalArticle

**Comment by mdoering** [comment]
We store references as CSL JSON - often not well parsed though as this is tough. But we should also try to use CrossRef services to lookup references to improve this somewhat.

**Comment by mdoering** [comment]
See the CSL section https://api.col.plus/dataset/1204/reference/1

**Comment by thomasstjerne** [comment]
Raises the question which style to actually use as default.
There seems to be at least 2000 to choose from: https://github.com/citation-style-language/styles
And theres a lot of locales to: https://github.com/citation-style-language/locales

**Comment by thomasstjerne** [comment]
Maybe I could pull all styles from the github api and let the user choose. But could be a bit overwhelming

**Comment by mdoering** [comment]
Yeah, we should pick a default one and _maybe_ allow the user to override that in his user settings.
Unless the library is far too large it would just allow us to switch styles and render things coherently.

@yroskov do you have a preferred known citation style? We should select sth frequently used in biologic, taxonomic or scientific high impact journals such as Nature?
https://subjectguides.library.american.edu/c.php?g=175008&p=1154150
