### ISSUE TITLE
Taxon page suggestions

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-frontend#199]
- [x] remove all lines in the indented "subsections" synonyms and classification
- [x] increase size of the name itself as it should be the visual number one
- [x] show rank & status on first line after name in one row, e.g. accepted species. In case of synonyms also show the accepted name as "{synonym status} for {accepted name}"
- [x] show publishedIn as 2nd information below name
- [x] render fossil and recent in one row with new label, e.g. Presence: Fossil & Recent
- [x] place origin and accordingTo last below classification in one row

**Comment by thomasstjerne** [comment]
@mdoering we don´t actually have fossil and recent anymore? Pls refresh my mind :-)

**Comment by thomasstjerne** [comment]
> In case of synonyms also show the accepted name as "{synonym status} for {accepted name}
There could never be a synonym taxon page.

**Comment by mdoering** [comment]
yes, we only have a single `extinct` flag now instead of recent & fossil.
As for synonyms we just need to make sure we always direct synonyms to their accepted taxon page.
Think we do that, so all good.
