### ISSUE TITLE
Login session bug

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#203]
I was logged in as the account colplus on prod, so I think there might be a login session bug. I logged out and back in again and now it's correct.

**Comment by mdoering** [comment]
This can happen when we wipe the database. Users are then inserted again and get a new key assigned which might swap with a previous one. In real production we never wipe the db again, so this wont happen.

Nevertheless I have changed the login procedure to use the username as the key, so swaps between users should not happen even after wipes
