### ISSUE TITLE
Provide form for UPDATE decisions

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#206]
A decision can either be of mode `BLOCK`, `REVIEWED` or `UPDATE` and `UPDATE_RECURSIVE`

Both update modes that various parameters from the decision object to update a taxon/synonym before its copied to the CoL. The recursive update also applies the values to all included taxa and synonyms (do we need to provide an option specify if the recursive mode applies to synonyms too?) .

All fields to supply updates with are (with example values):
```
{
  "name": {
    -- entire name instance
  },
  "status": "PROVISIONALLY_ACCEPTED",
  "fossil": true,
  "recent": false,
  "lifezones": ["brackish, "marine"]
}
```

Only fields that are non null will be updated. Null/missing fields are ignored and kept as is.
Important fields in the name instance that should be useful are:

-  Name.code
-  Name.nomStatus
-  Name.type
-  Name.rank
-  Name.authorship

Ideally the UI provides a full NameUsage form will all available options and the entire parsed name object: https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/model/Name.java#L25

**Comment by thomasstjerne** [comment]
I think we need to distinguish between a status update decision and decisions that changes the name.
The current frontend logic deals with decisions in batch mode, e.g. set status = provisionally accepted for all selected taxa.

In the UI an update on the name would look more like an actual edit of the data than applying a decision.
So maybe sth like: `STATUS_CHANGE`,  `BLOCK`, `REVIEWED`,  `UPDATE_NAME`.

The recursive update seems dangerous when it is possible to overwrite name attrs.

**Comment by mdoering** [comment]
potentially dangerous yes, but should we not trust the editor to do sensible things? Its also non destructive and can be revoked. 

Updates are also applicable to the taxon, not just the name. Updating the fossil flags or lifezones most notably. The recursive update is mostly for applying fossil flags and lifezones to all children if I recall correctly.

If we restrict UPDATE_NAME to just name attributes we cannot change both for the same taxon as there can only be a single decision per usage.
