### ISSUE TITLE
Show SectorDeletes differently in sync list

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#212]
The assembly sync list contains both SectorSync and SectorDeletes.
Deletes should be marked somehow and the "Sync" button should be missing as there is nothing left to sync.

**Comment by thomasstjerne** [comment]
Currently I don´t see any deletes in the sync list. (I have done deletions, so they should be there)

**Comment by mdoering** [comment]
they do run, but seems the serialization doesnt tell you what it is. I should probably add polymorphic type infos in json

**Comment by mdoering** [comment]
with the next deploy there should be a `type` attribute that is either `SectorSync` or `SectorDelete`
