### ISSUE TITLE
Show currently syncing sector name

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#216]
in assembly it would be nice to know which sector/dataset is currently being synced

**Comment by thomasstjerne** [comment]
Currently that would be only one at a time - but how about prod, there could be many right?

**Comment by mdoering** [comment]
The plan is to always leave that at one at a time per catalogue - otherwise I might run into concurrent insert troubles.

**Comment by mdoering** [comment]
The sync state object also has just a single property and no list
http://api-dev.col.plus/assembly/3
