### ISSUE TITLE
Add missing TAXON_ID filter to name usage search

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#220]
to restrict search results to a higher taxon the TAXON_ID filter should be exposed in the name (usage) search. As it takes a taxonID we need to implement a lookup similar to the GBIF occurrence search

**Comment by ayco-at-naturalis** [comment]
Yes, that's indeed a useful feature

**Comment by mdoering** [comment]
the filter is already working. what is the exact work to be done? ids are retrieved from the very same search
