### ISSUE TITLE
Show estimates and allow changes

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#225]
Species estimates are now another kind of decision with its own API resource, see https://github.com/Sp2000/colplus-backend/issues/217

The Tree API returns an estimate object for the catalogue, if existing, that should be shown in the tree. Updates, create/delete should be possible by talking to the estimate resource directly.

The API also exposes broken estimates and a way to rematch them - similar to the other decisions

**Comment by mdoering** [comment]
Available on prod now and dev shortly:
https://api.col.plus/dataset/3/tree

They became lists after Sp2000/colplus-repo#31

**Comment by mdoering** [comment]
Not sure if we should show lists directly.
I reckon we should rather calculate a single estimate and then allow to see the list of estimates with their source reference when opening up details.

To calc estimates we could
 - a) calc the average
 - b) use the latest estimates according to the updated/created timestamp
Ultimately we could do this in the backend and expose a single estimate in the tree API.
@yroskov @gdower @thomasstjerne @olafbanki what method should we pick for now?

**Comment by thomasstjerne** [comment]
I will design the tree to expect one estimate. Whether that is picked or calculated on the frontend or delivered from the backend can then be decided

**Comment by mdoering** [comment]
The Tree API will expose an `estimate` property with the average for now

**Comment by thomasstjerne** [comment]
Should it be possible CRUD on estimates, or are they coming from the GSDs?

**Comment by mdoering** [comment]
estimates are currently managed by the catalogue editor(s) and there is a CRUD resource for them, see https://github.com/Sp2000/colplus-backend/issues/217

Potentially they might also come from GSDs, but that is not happening now

**Comment by mdoering** [comment]
so yes, the list of estimates with estimate & referenceID needs to be editable incl create & delete.
And it would be good to have a first stab at a reusable reference editing component that allows to lookup or enter a new reference

**Comment by thomasstjerne** [comment]
Do we have a search on references?
In order to autocomplete for the referenceID

**Comment by mdoering** [comment]
ah, not done yet. But I can do one rather quickly if we know what the search should be like.
A basic full text search and potentially separate filters for author and year maybe?

**Comment by mdoering** [comment]
working on https://github.com/Sp2000/colplus-backend/issues/25 now

**Comment by mdoering** [comment]
see also https://github.com/Sp2000/colplus-backend/issues/397 on how to post refs

**Comment by mdoering** [comment]
ref search deployed, but sth not right with the full text index. This is how it should work:
https://api.col.plus/dataset/1010/reference/search?q=Congridae

searching by year works:
https://api.col.plus/dataset/1010/reference/search?year=1999
