### ISSUE TITLE
Searchable verbatim browser

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#236]
In order to find arbitrary entry points to the data browser we could make "verbatim" a permanent entry in the dataset menu and provide a few filters at the top:

 - a rowType "facet" taken from the import metrics just as we show them in the metrics pie
 - a full text free search form 
 - a term filter with a dropdown of all available terms ([needs a new API method](https://github.com/Sp2000/colplus-backend/issues/497)) and a freetext form to place a value

The results could/should also be made pageable, but otherwise be just like the verbatim view is now.

**Comment by gdower** [comment]
Being able to search on verbatim data would be really useful. @mdoering, is there anything like ?q= parameter that would search across all verbatim fields? It looks like it's possible to search on some verbatim fields (subGenusName, speciesEpithet, authorString but not genus?) although it's not in the [API documentation](https://sp2000.github.io/colplus/api/api.html#resource-4):

Works:

http://api.col.plus/dataset/1005/verbatim?subGenusName=Unplaced&type=AcceptedSpecies
http://api.col.plus/dataset/1005/verbatim?speciesEpithet=hirsutistyla&type=AcceptedSpecies
http://api.col.plus/dataset/1005/verbatim?type=AcceptedSpecies&authorString=Alexander,%201963

Doesn't work:

http://api.col.plus/dataset/1005/verbatim?type=AcceptedSpecies&genus=Tipula
http://api.col.plus/dataset/1005/verbatim?q=Unplaced
http://api.col.plus/dataset/1005/verbatim?name=Unplaced

**Comment by gdower** [comment]
I figured it out, the fields are supposed to be capitalized, not camelCase:

http://api.col.plus/dataset/1005/verbatim?type=AcceptedSpecies&Genus=Tipula

**Comment by mdoering** [comment]
The field names are case sensitive, exactly as their defining term names are.
For ACEF that is UpperCamelCase, but DwC uses lowerCamelCase for property terms (but UpperCamelCase for class terms like *Occurrence*). It's just as these standards have been defined.

**Comment by mdoering** [comment]
The backend now also offers a full text `q` query parameter that searches any values.
Implemented in https://github.com/Sp2000/colplus-backend/commit/0c1fc32f1ad5f559d3ad596eac399ec53e458354

**Comment by mdoering** [comment]
http://api.col.plus/dataset/1005/verbatim?q=Tipula
