### ISSUE TITLE
No paging possible for Importer queue

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#239]
the importer queue seems to have a fixed page in the UI:
https://www.col.plus/imports/running?limit=25&offset=0&state=downloading&state=processing&state=inserting&state=indexing&state=building%20metrics

If the API returns 100 imports it is impossible to get to the last ones and cancel them.
Add paging!
https://api.col.plus/importer/queue?

**Comment by thomasstjerne** [comment]
It seems that paging is not enabled for the queue: https://api-dev.col.plus/importer/queue

It would be better if the queued import was included here: https://api-dev.col.plus/importer?state=queued

The paging is based on the response from https://api-dev.col.plus/importer (which is currently usually only three entities)

**Comment by mdoering** [comment]
So basically a single resource for all importer (and similar sync) attempts, no matter if queued, running or historical. Ordered chronologically. Makes a lot of sense.

Only thing is they return different objects right now. 
ImportRequest for the queue and DatasetImport for historical ones.
I guess it should then all be instances of DatasetImport. Created new issue https://github.com/Sp2000/colplus-backend/issues/404 for it

**Comment by mdoering** [comment]
Hm, if we order chronologically the queue would be in the future, coming before the actual running ones. Does that cause problems? I guess as long as we have a filter/switch in the UI to show only currently running ones this is fine

**Comment by mdoering** [comment]
A bit like the Oozie web console

![Oozie-Web-UI-Oozie-Tutorial-Edureka-1](https://user-images.githubusercontent.com/327505/59925712-fe7a0600-9438-11e9-9936-e07438294ead.png)


<img width="1154" alt="Screenshot 2019-06-21 at 15 26 31" src="https://user-images.githubusercontent.com/327505/59925721-046fe700-9439-11e9-9637-01aed45893ae.png">

**Comment by mdoering** [comment]
Merged queue API into importer API, see https://github.com/Sp2000/colplus-backend/issues/404

**Comment by mdoering** [comment]
paging wrapper with counts exposed in merged API:
http://api-dev.col.plus/importer?offset=10
