### ISSUE TITLE
How to deal with language codes & titles

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#244]
The backend wants to treat languages as ISO3 codes primarily.
The frontend should at some point visualize them by their english title/name, see current UI:
http://www.catalogueoflife.org/col/details/species/id/27f8272c42efe9f73dbaa996ea587da7/common/22b688fb8d868091ea1d7543673122e9

As there are 7700 registered languages keeping a mapping in memory might be too heavy for the react client. Should there be a vocab service that resolved them?

**Comment by mdoering** [comment]
see https://github.com/Sp2000/colplus-backend/issues/159

**Comment by thomasstjerne** [comment]
Yes, a get language name by code would be good.

**Comment by mdoering** [comment]
- list all codes with their titles: http://api.col.plus/vocab/language
 - list a title for a given code: http://localhost:8080/vocab/language/gsw
