### ISSUE TITLE
Show source dataset with logo on taxon pages

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#246]
For the draft catalogue we should show the sector/dataset it originates from similar to the current UI: 

<img width="1247" alt="Screenshot 2019-06-18 at 11 19 28" src="https://user-images.githubusercontent.com/327505/59669691-fad94b80-91ba-11e9-87b1-c5d7632a7c16.png">

This can be done via the sectorKey which is only present on assembled catalogues.
The sector contains the datasetKey which in turn can be used to grab the logo.

**Comment by thomasstjerne** [comment]
Could we add the logoUrl in the dataset response: https://api.col.plus/dataset/1164
Currently the UI tries to fetch a logo, and then ingores a 404: https://api.col.plus/dataset/1164/logo

This would also save some requests since the UI wont have to check if the logo is there

**Comment by mdoering** [comment]
I guess we could. But it conflicts with the logoUrl already present - which is only for external logos which we then harvest and process into 3 sizes. All of which you can ask for from the API. Bzw. please indicate which sizes you would line to see generated!

**Comment by mdoering** [comment]
Does it really save a request? You need to download the image anyways
