### ISSUE TITLE
Unable to apply decision nameType=SCIENTIFIC

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#250]
in https://www.col.plus/dataset/1010/workbench?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Foa%20fo

It also needs one to go to the workbench interface when you are already in the assembly tree it would be nice to apply a decision also in the source view there. Or maybe simpler and more powerful to link to the workbench from there?

**Comment by mdoering** [comment]
... how can I apply a full, advanced decision?

**Comment by thomasstjerne** [comment]
> ... how can I apply a full, advanced decision?

You leave the picklist blank and click "Apply decision" this opens the full form

**Comment by mdoering** [comment]
Ah, should we maybe add an "other" entry or sth like that to open the form?
