### ISSUE TITLE
Manage imports

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#27]
List currently running and queued imports.
Allow to cancel running or queued imports and schedule new ones

**Comment by thomasstjerne** [comment]
Currently endpoints are scoped by dataset - should we have a base endpoint for imports to show all running imports, etc?

**Comment by mdoering** [comment]
we do already, its part of the undocumented admin API I am about to merge this week:
http://admin.col.plus/importer?limit=500
http://admin.col.plus/importer?state=failed

And this is the current queue of import jobs which can be canceled:
http://admin.col.plus/importer/queue
