### ISSUE TITLE
Cannot attach sectors to taxa highlighted as search matches

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#271]
In assembly when trying to attach a sector to a taxon found by search, I get the error message, "You cant modify the CoL draft in attachment mode." 

![Cannot attach to search result](https://user-images.githubusercontent.com/8573609/60466996-e82f2f80-9c1a-11e9-89e5-abb56db03a87.png)

Manually expanding the CoL Draft tree to the same taxon allows attaching with the same sector:

![Can attach to manually expanded tree](https://user-images.githubusercontent.com/8573609/60467056-190f6480-9c1b-11e9-9bd3-1f41c1f64e2a.png)

(I'm just testing the attach functionality somewhere else because [section deletion is broken](https://github.com/Sp2000/colplus-backend/issues/373).)

**Comment by thomasstjerne** [comment]
Thanks @gdower 
I was not able to get the same error message as you - however, I was not able to attach sectors to highlighted taxon nodes either. I think I have now fixed this, but could you please check if you still get the error message?

**Comment by gdower** [comment]
Thanks, @thomasstjerne, that fixed it.

**Comment by gdower** [comment]
I'm reopening this, because it's actually still a problem. The exact steps to reproduce are:

1) search for Merostomata in to the CoL draft search of [Assembly](https://www.col.plus/assembly) (left search input)
2) click on suggested Merostomata search result
3) click on Merostomata sector attachment point
4) click show sector in source button
5) drag and drop the Merostomata class from the dataset source on the right onto the Merostomata class on the left CoL draft

It will display the warning message that, "You cant modify the CoL draft in attachment mode."

If after step 5 above you expand another kingdom, it does allow attachment of Merostomata to a phylum or class in any other kingdom.

If you manually expand the CoL draft to the Merostomata attachment point (without using search) and search for the Merostomata dataset in the right search pane, it is possible to attach the sector, which is what I'd expect to happen. If you click OK, it will throw a non-unique key error because the sector is already attached, but I would expect that and am testing for it.
