### ISSUE TITLE
Past decisions are not displayed in the duplicates tool

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#274]
See [Sp2000/colplus-backend#426](https://github.com/Sp2000/colplus-backend/issues/426) for a description of the bug.

**Comment by thomasstjerne** [comment]
@gdower can you test whether this has been fixed by https://github.com/Sp2000/colplus-frontend/issues/278

**Comment by gdower** [comment]
@thomasstjerne, I tested prod and the frontend still isn't showing that the two synonyms on [this page](https://www.col.plus/dataset/2048/duplicates?authorshipDifferent=false&category=trinomial&limit=50&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=false) are ambiguous synonyms even though the [decision has been applied](https://api.col.plus/decision?datasetKey=2048). It also doesn't work on dev ([frontend](https://dev.col.plus/dataset/2070/duplicates?authorshipDifferent=false&category=trinomial&limit=50&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=false) with no decisions displayed vs [api-dev with decisions remembered](https://api-dev.col.plus/decision?datasetKey=2070)). 

The same bug seems to not [display blocked decisions](https://dev.col.plus/dataset/2070/duplicates?authorshipDifferent=false&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&parentDifferent=false&status=synonym&withDecision=false) either (even when withDecision == true), but [provisionally accepted decisions are correctly displayed](https://www.col.plus/dataset/2048/duplicates?authorshipDifferent=false&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=true) (withDecision == true).
