### ISSUE TITLE
Importer status always polled

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#291]
The importer status should only be polled when needed, i.e. when the import pages are shown. It is currently polled even when on a dataset page:

<img width="1430" alt="Screenshot 2019-08-16 at 10 06 53" src="https://user-images.githubusercontent.com/327505/63153092-c264bb00-c00d-11e9-933f-1de7cd1a8412.png">

**Comment by thomasstjerne** [comment]
The import metrics page needs to know the import status as it will show the state if the dataset is currently being imported.
