### ISSUE TITLE
Check most recent and check all except oldest buttons not working

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#296]
When clicking the most recent and check all boxes in the [duplicates tool](https://www.col.plus/dataset/1702/duplicates?authorshipDifferent=true&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false), it doesn't do anything. There's no API requests (although this functionality might be purely handled by the frontend) and no browser console errors.

**Comment by thomasstjerne** [comment]
It compares the publishedInYear - so at least two names in a duplicate group must have this field set for anything to be selected. Names without publishedInYear will never be selected.

I have added some tooltips explaining this
