### ISSUE TITLE
Improve MERGE sector visualisation

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#298]
A single merge sector can be responsible for many child nodes which we visualize in the assembly tree just as any other (attach) sector. This is misleading. E.g ITIS is responsible for all of the Bacteria, but it feels like tens of individual sectors:

<img width="754" alt="Screenshot 2019-08-19 at 15 36 15" src="https://user-images.githubusercontent.com/327505/63269886-4aa9c100-c297-11e9-88e3-8e81ca518edc.png">

This has been discussed in circles, but I think I would prefer a single sector to sit on Bacteria somehow labelled as a merger.

**Comment by mdoering** [comment]
@yroskov @gdower input very welcome

**Comment by yroskov** [comment]
In your example, ITIS banner should be present with kingdom Bacteria as well as with all children taxa beneath.

**Comment by mdoering** [comment]
it is not only the banner which indicates the origin of the data. But also the > indicating an actionable sector

**Comment by mdoering** [comment]
maybe the merged kingdoms are a special case. they really are attached to the “Biota“ root of the tree. What if we had a (potentially hidden) root node Biota? or an empty sector target for the root?
