### ISSUE TITLE
u[(u.length - 1)] is undefined in assembly tree

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#301]
@yroskov found a bug on dev where once a new sector is attached it disappears from the Assembly tree and the frontend displays the following error:

![image](https://user-images.githubusercontent.com/8573609/63366844-3b328280-c340-11e9-9f57-daa56d221ee7.png)

This same error occurs sometimes when assemblyTaxonKey= is in the URL for a sector that is missing (or maybe being processed?).

**Comment by gdower** [comment]
[Cycadopsida is in the search index.](https://api-dev.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Cycadopsida) However, if you add the [assemblyTaxonKey=8deceba7-a552-44d2-b37a-a2029c2b70b4](https://dev.col.plus/assembly?assemblyTaxonKey=8deceba7-a552-44d2-b37a-a2029c2b70b4) URL parameter, it reproduces the frontend bug.

**Comment by thomasstjerne** [comment]
It seems Cycadopsida has different id´s in the search index and in the tree api (called to expand the tree, fetch children etc).

Cycadopsida in the search index: 8deceba7-a552-44d2-b37a-a2029c2b70b4
Cycadopsida in the tree api: d6458ee7-17ca-4835-b4f7-f190fd58e97a

The frontend now catches this and reports an error that it could not find the taxon in the tree. 

I have opened an issue for the id inconsistency here: https://github.com/Sp2000/colplus-backend/issues/446
