### ISSUE TITLE
Importer queue performance

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#304]
It seems like the [importer queue](https://www.col.plus/imports/running?limit=25&offset=0&state=downloading&state=processing&state=inserting&state=indexing&state=building+metrics) is sending huge numbers of requests for information from every dataset in the queue:

http://api.col.plus/dataset/ `[ID]`

I'm not really sure why, because it seems like all of the info needed by the import queue is available with 1 request to /importer, but maybe there's a good reason for it:

http://api.col.plus/importer

Also, I think the refresh rate to the importer API call is set too fast. Probably updating every 20 seconds would be alright.

**Comment by thomasstjerne** [comment]
http://api.col.plus/importer gives only datasetKey. In order to display the title of the dataset in the import table, it has to fetch each one
