### ISSUE TITLE
How to reattach a broken sector

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#308]
if a target ID is not found, offer a button on the right to "reset target" and set the ID to NULL so it shows as a broken sector.

A subsequent drag to the assembly tree then reattaches the sector target (PUT) instead of blocking a POST create.

Visualize broken sectors in the source and assembly tree somehow (asterisk or dead symbol?)

**Comment by thomasstjerne** [comment]
the frontend now catches a missing id on lookup in the assembly and gives a text suggesting to delete the sector and create a new one. Also once a lookup has failed, sectors having that target id will show a small exclamation mark
