### ISSUE TITLE
Preload decision data for a single name

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#313]
When we want to apply a new scientificName, authorship or sth else with a decision it is cumbersome and errorprone to enter the data from scratch.

It would be ideal if we would prefill each form field separately whenever we enter it and it was empty before (instead of loading the entire form cause we usually only want to overwrite one or two fields not the entire info)

**Comment by thomasstjerne** [comment]
Not shure I understand. If theres a decision already, data should be prefilled from that decision. 
I assume that if you want to change, say Authorship, you only have to fill in that value and post it the server, I.e. it doesn´t need to include rank, lifezones, nom status etc etc

**Comment by mdoering** [comment]
Yes, but when correcting data it would be convenient, faster and less error prone to not enter the data manually, but just edit the current name records field. I.e. You load the authorship from the name record to be then manually corrected

**Comment by thomasstjerne** [comment]
OK. But then you you would probably often get a decision with a scientific name that is unchanged, but will be present in the decision. It might be harder to actually see what was changed

**Comment by mdoering** [comment]
No, just load the form field someone activates, not the entire form

**Comment by mdoering** [comment]
it would also be really good if you could work on the selected list from the workbench and simply edit the next record without the need to save n close the form first.
