### ISSUE TITLE
Taxa of different ranks are shown in the same line in the Tree

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#321]
Catalogue - Assembly
When I expand phylum Zygomycota, children Classes, Orders & Genera are shown on the same branch level. 
![image](https://user-images.githubusercontent.com/28574252/63971424-058e4780-ca6c-11e9-945e-69f9fed4a5db.png)

Please try to improve presentation and make its look closer to AC interface: http://www.catalogueoflife.org/col/browse/tree/id/cb94533daba0f1cfbd73a9a95eb02a2c  
![image](https://user-images.githubusercontent.com/28574252/63963041-b8a17580-ca59-11e9-9cd9-6013f02f3e0b.png)

**Comment by mdoering** [comment]
this is blocked by the existing [backend issue 375]( https://github.com/Sp2000/colplus-backend/issues/375)
