### ISSUE TITLE
Misplaces cases "same parent" in duplicates reports

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#324]
Cases ACC-SYN & SYN-SYN where binomial/trinomial synonym is identical to its parent or neighbor accepted name, should be reported as SAME PARENT (now they are in the report "different parent").

In addition, Markus suggested to use word "accepted" instead of "parent" in the title of the reports, i.e. ACC-SYN species (same accepted, different author). I have no objection to this.

![image](https://user-images.githubusercontent.com/28574252/63970730-7cc2dc00-ca6a-11e9-85d9-0f061fc419c9.png)

**Comment by mdoering** [comment]
see https://github.com/Sp2000/colplus-backend/issues/456

**Comment by mdoering** [comment]
backend changed to use `acceptedDifferent` parameter
