### ISSUE TITLE
Problems with my account/permissions?

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#325]
www.col.plus
Frontend version: 3b50e4e August 29, 2019 6:41 AM
Backend version: c09aac5 August 28, 2019 7:12 AM

Today I was not able to perform any drag&drop actions in _Catalogue-Assembly-AttachSectors_ at www.col.plus. Every time I have got error messages such as:
Request failed with status code 500
There was an error processing your request. It has been logged (ID 426abf1a8fb740f4).
HTTP method: POST
https://api.col.plus/sector
Body:
{"datasetKey":1166,"mode":"ATTACH","subject":{"id":"xr71o","status":"accepted"},"target":{"id":"c8318d67-6ae3-40b3-baea-d01828e977d3","status":"accepted"}}

Request failed with status code 500
There was an error processing your request. It has been logged (ID 362877bc15dedd00).
HTTP method: POST
https://api.col.plus/sector
Body:
{"datasetKey":1162,"mode":"MERGE","subject":{"id":"xabgo","status":"accepted"},"target":{"id":"2d58c70d-f72f-43a6-9dbf-e7e8ef0ac7cb","status":"accepted"}}

Request failed with status code 500
There was an error processing your request. It has been logged (ID 8c41b165e8786b5f).
HTTP method: POST
https://api.col.plus/sector
Body:
{"datasetKey":1141,"mode":"ATTACH","subject":{"id":"x5ZR7","status":"accepted"},"target":{"id":"2d58c70d-f72f-43a6-9dbf-e7e8ef0ac7cb","status":"accepted"}}

The same actions were permitted withot errors through Geoff account.

What and where is wrong?

**Comment by gdower** [comment]
I checked and @yroskov's account has the exact same roles that I have in the API:

roles	
0	"user"
1	"editor"
2	"admin"

I'm not sure whether these bugs are due to authentication or maybe the process fails the first few times and works for me. Yuri and me are both using the exact same version of Firefox (although on Windows vs Linux).

**Comment by yroskov** [comment]
I have had 4 attempts to merge Fabaceae from WPlants in the tree. The same error:
Request failed with status code 500
There was an error processing your request. It has been logged (ID 07d74d34e2a49200).

**Comment by gdower** [comment]
Here's some of the error IDs that Yuri got: [be66b073f6b50624](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(analyze_wildcard:!t,query:be66b073f6b50624)),sort:!('@timestamp',desc)))
ID [fe80da2e23273f0e](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(analyze_wildcard:!t,query:fe80da2e23273f0e)),sort:!('@timestamp',desc)))

**Comment by gdower** [comment]
@yroskov was trying to add the genus Astragalus to the family Fabaceae, but was getting the same error as above. To rule out it being a problem with his computer, I logged in to CoL+ on his computer as as `gdower` and was able to create the genus without an error, so I think this is  a user permissions problem.

@mdoering, there are some slight differences between our accounts in the API, although I'm not sure if it matters that @yroskov doesn't have a key?

```
GET /user/me
username	"yroskov"
email	"yroskov@illinois.edu"
country	"US"
roles	
0	"user"
1	"editor"
2	"admin"
lastLogin	"2019-08-30T19:23:20.11"
```

```
GET /user/me
key	100
username	"gdower"
firstname	"Geoff"
lastname	"Ower"
email	"gdower@illinois.edu"
country	"US"
roles	
0	"user"
1	"editor"
2	"admin"
lastLogin	"2019-08-30T18:00:28.745"
```

**Comment by mdoering** [comment]
status code 500 is a backend error, not permissions.
Permissions will be a 401 or 403 error

**Comment by mdoering** [comment]
Yes, the missing key is the problem indeed. 
I bet it is related to a deploy when then client token still persists. @yroskov could you please logout and login again in such cases? That should solve it.

I will try to find out why that actually happens

**Comment by mdoering** [comment]
I have updated the jwt library and some login checks, but Im not entirely sure why this can even happen. As it is related to wipes this will stop anyway soon. Just logout and back in again
