### ISSUE TITLE
Taxa unexpectedly changed its Is_Extinct status from living to extinct

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#331]
In latest conversion from CoL+ to production interface of 2019-09-01, **1,472** species have unexpectedly changed their status from
For example, entire phylum Acanthocephala with 1,330 living species jumped from "living" to "extinct" (there no extinct species in this phylum in CoL).
Where the problem is?

**Comment by yroskov** [comment]
CoL+ shows: 
Fossil No
Recent No

**Comment by mdoering** [comment]
No, it should be fossil:null, recent:null as it is in the assembled CoL+ catalogue.
The bad mark in the AC interface must come from either the export or the conversion. It is surely not a frontend issue

**Comment by mdoering** [comment]
closing in favor of https://github.com/Sp2000/ConversionTool/issues/9
