### ISSUE TITLE
r.data.result is undefined in running imports queue

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#339]
I'm getting an ```r.data.result is undefined``` error in the running imports queue, but the backend looks okay (no imports were running):

```
{"offset":0,"limit":10,"total":0,"last":true,"empty":true}
```

Frontend version: 355cf0c September 9, 2019 7:33 AM
Backend version: 530045e September 9, 2019 11:45 AM

Probably related to #336

**Comment by thomasstjerne** [comment]
> Probably related to #336

Yes, its the frontend hack I made :-/
