### ISSUE TITLE
add download link to admin pages

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#340]
Please add a link to the downloads on the admin page which include the catalogue ac-export file. Maybe also add a notification when the AC export has finished that you find the generated archive there:

PROD:
http://api.col.plus/download/

DEV:
http://api-dev.col.plus/download/

**Comment by gdower** [comment]
@thomasstjerne, the download link on the [admin page](https://www.col.plus/admin) needs to be http:// not https://. Linking to it is a nice enhancement. :+1:

**Comment by gdower** [comment]
@thomasstjerne, I think line [455](https://github.com/Sp2000/colplus-frontend/blame/6e85fd0de0316042fbf1fe67a8a900990abfae86/src/pages/Admin/index.js#L455) should be:

```<a href={config.downloadApi}>here</a>```

Otherwise there's the https problem again because the download service is actually running on port 80.
