### ISSUE TITLE
Adjust to new DatasetType.CATALOGUE

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#359]
For assembled catalogues like the draft CoL, all its releases and the future provisional catalogue there is a new dataset.type=CATALOGUE to identify them.

Adjust dataset search and other relevant places to use it

**Comment by thomasstjerne** [comment]
It will popup anywhere the enum is used without any changed.
I will add the column to the dataset search, but which query param should be used? Seems that neither [type](https://api-dev.col.plus/dataset?type=catalogue&limit=20&offset=0&reverse=false) nor [datasetType]( https://api-dev.col.plus/dataset?datasetType=catalogue&limit=20&offset=0&reverse=false
) does the filtering

**Comment by mdoering** [comment]
parameter `type` should be it

**Comment by mdoering** [comment]
will be fixed in next backend version
