### ISSUE TITLE
How to update a name in a decision?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#360]
We currently have 3 form fields for updating the core name information in an editorial decisions: `scientificName`, `authorship` and `rank`. A Name object in the API contains a lot more parsed out properties though (see below). To populate those we have two options:

**A)** We stick with the 2 above form fields and parse out the name in the backend whenever we need to apply the decision. This is what is currently implemented.

**B)** We allow the editors to fully manipulate all of the Name properties. As this can be tedious we would allow to enter a single name string which the UI parses using the name parser API and then sticks into the detailed form fields.

The advantage of A) is that is simpler to deal with decisions. The advantage of B) is that we can override any name parser problems that we might encounter. E.g. when the name parser did not handle the authorship like [Schaufuss, L. W.](https://github.com/gbif/name-parser/issues/28) correctly we could have fixed such names (if they are rare isolated cases) with such a decision while we are already in production mode and would not have to wait for a parser update. 

@gdower @yroskov @thomasstjerne what is your preference here?

All name properties that we would need a form for are these which is quite a few:
 - scientificName
 - authorship
 - type (enum)
 - rank (enum)
 - uninomial
 - genus
 - infragenericEpithet
 - specificEpithet
 - infraspecificEpithet
 - cultivarEpithet
 - candidatus (bool)
 - notho (enum)
 - combinationAuthorship:
    - authors (array)
    - exAuthors (array)
    - year
 - basionymAuthorship:
    - authors (array)
    - exAuthors (array)
    - year
 - sanctioningAuthor
 - appendedPhrase

**Comment by yroskov** [comment]
A or B: all depends on whether CoL+ Workbench will do correction job (new development) or the job should be done at the stage of preparation of data (workflow of previous years). A (interface might be too complicated) or B (still requires a lot of programmatic work for each GSD) - I need to hear Geoff's opinion.
Another problem, how we'll identify bugs such as "Schaufuss & L. W." (and probably hundred others)?

**Comment by mdoering** [comment]
A or B are both slightly different ways of applying decisions, so they both correct data in CoL+ not during data preparation. In that regard they are the same. It is mostly a UI usability question.
