### ISSUE TITLE
Adapt to changed tree API

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#361]
The tree API had to be changed to include a new query parameter `catalogueKey` that defines the catalogue context in which the tree is viewed. In the current UI this should always be 3 for the draft, but when we visualize other catalogues and their releases this can change. Even when a source tree is browsed we need to also know about the catalogue as e.g. there might be several sectors all pointing to the same source id, but coming from different catalogues.

**Comment by thomasstjerne** [comment]
I guess it doesn´t apply to the recursive delete?

**Comment by mdoering** [comment]
correct! just the others: root, get & children

**Comment by mdoering** [comment]
The API will default catalogueKey=3 with the next deploy
