### ISSUE TITLE
Multi decision apply error in workbench

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#366]
When applying decisions to multiple selections the new numbered selector is great!
But when I went back to a decision I already have submitted I got an error cause it seems to create another decision instead of updating it. This can happen quite easy as one can select any number on the right and freely jump forward/backwards and to any point in the list.

<img width="1564" alt="Screenshot 2019-10-09 at 13 51 16" src="https://user-images.githubusercontent.com/327505/66479186-4aaa8e00-ea9c-11e9-8299-b4bc6ce26279.png">

**Comment by thomasstjerne** [comment]
Gotcha
