### ISSUE TITLE
Workflow: from Issues jump to Workbench

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#387]
Menu item **Issues**.
Present behavior: when I click on count figure in the list of issues, front end software directs me to the page **Names**, where I cannot apply any decisions. 

Expected behavior: when I click on count figure in the list of issues, front end software should direct me to the page **Workbench**, where decisions can be applied. 

(see also github issue #353 - do we really need page Names?)

**Comment by mdoering** [comment]
agree and would propose to merge workbench and names search. It should rather depend on the user role to see options to apply decisions
