### ISSUE TITLE
Filter dataset search on contributesTo

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#389]
The dataset search shows the `contributesTo` property but does not allow to sort or filter on it. At least filtering for datasets that do contribute to a given catalogue or no catalogues at all would be useful. Sorting is maybe not needed and probably difficult for the backend.

**Comment by mdoering** [comment]
we could just start with a filter for the "CoL draft = 3" only

**Comment by mdoering** [comment]
this is really essential to understand the state of all source datasets in the Clearinghouse

**Comment by thomasstjerne** [comment]
Is it possible to query the dataset API for all assembled datasets, i.e. get a complete list of which possible values the `contributesTo ` could have?
Would it simply be http://api.dev.catalogue.life/dataset?origin=managed ?

**Comment by mdoering** [comment]
All of type=CATALOGUE could in theory have sectors.
But I guess we should better expose a new method that lists datasetKeys used in existing sectors.

**Comment by mdoering** [comment]
There will be a new method `/dataset/catalogues` soon that return the list of all dataset keys that have at least one sector.
