### ISSUE TITLE
Taxon details classification order random

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#399]
The classification order is sometimes (seems random) reversed.
It should always be kingdom down to genus

<img width="685" alt="Screenshot 2019-11-05 at 10 51 25" src="https://user-images.githubusercontent.com/327505/68197312-56fe0a00-ffba-11e9-86f2-0924be782f66.png">

<img width="676" alt="Screenshot 2019-11-05 at 10 51 34" src="https://user-images.githubusercontent.com/327505/68197313-5796a080-ffba-11e9-974f-b083c2112d65.png">

https://www.col.plus/dataset/1027/taxon/x66S

**Comment by thomasstjerne** [comment]
The frontend does not sort the [classification](https://api.col.plus/dataset/1027/taxon/x66S/classification), only reverses it. I would think it is the API sometimes flipping the order, is that possible?

**Comment by mdoering** [comment]
Not that I can see, no. This always returns the genus as the first entry:
https://api.col.plus/dataset/1027/taxon/x66S/classification

But the frontend sometimes doesnt
