### ISSUE TITLE
Let's optimize the Tasks page

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#405]
Working on Scarabs database, I understood what should be done to improve convenience of Tasks page.
User need to know which task he already completed or partially completed in editorial process. (As shortcut solution, I printed out a screenshot of Tasks and keep marking completed tasks on a paper and adding initial number of issues in the task).
Two improvements which we need in Tasks page:
1) Please **freeze default order of tasks** (at present, dynamic sorting of tasks is implemented:  tasks with higher number of issues are in the top of the list; as soon as issues fixed (i.e. decisions applied), the task goes down). Expected behavior: order of tasks is fixed, and it is the same through all GSDs. Only colour of the box will indicate priority of the task (as it implemented now).   
2) Please **add a number of remaining issues of total** in each "task box", for example "0 of 4", "5 of 31", "243 of >50", something like that: 
![image](https://user-images.githubusercontent.com/28574252/68330168-62276780-0098-11ea-879a-6fc09b334bb3.png)

**Comment by thomasstjerne** [comment]
Makes sense. And by completed tasks we mean duplicates that has a decision, i.e. they have been adressed.
It made me think that we at some had a discussion about having a decision that simply said "no decision" or "reviewed", indicating that this has been inspected. 
You would only get to the bottom of a task group by applying decisions on all duplicates

**Comment by mdoering** [comment]
see https://github.com/Sp2000/colplus-backend/issues/555

**Comment by yroskov** [comment]
Thank you @thomasstjerne for implementation! Minor request for further improvement: could you please take off word "completed" and keep only figures such as "2 of >50". And implement format "0 of 0" if no issues. 
This will minimize shift of bars on the page which depended on text length. Stable position of bars helps in completing task.

**Comment by yroskov** [comment]
Thank you @thomasstjerne! 
Completed task looks now as "2 of 0" (green). Would it be possible to change presentation as 
"2 of 2" (green) for two issues completed of two initially reported; 
"5 of 7" (orange) for five issues completed of seven initially reported;
"0 of 16" (red) for null issues completed of sixteen initially reported.
i.e. to keep total number of initial issues.  
"0 of 0" if there were no issues initially).
