### ISSUE TITLE
What logo sizes are needed

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#408]
What logo sizes are needed by the frontend? Right now we prepare 4 sizes:

-  ORIGINAL: as it was given
-  LARGE: 200x600
-  MEDIUM: 100x300
-  SMALL: 30x90

Do these sizes and ratios make sense? For exporting to the old portal we need 30px and 100px height images, but that could be legacy sizes we only maintain until we close the old portal.

Judging the existing logos many of these are more then twice as wide as high. And maybe a square one is needed which we would crop?

**Comment by thomasstjerne** [comment]
I guess we could just use GBIF Thumbor for this?

**Comment by mdoering** [comment]
probably, but then the original design was to be as independent from GBIF systems as possible to allow migration away from GBIF if wanted at some stage. 

We already have the image upload, resizing and caching in place, so unless you get some real benefit from thumbor I'd use what is there. If you need different sizes than the ones listed above please leave a ticket in the backend
