### ISSUE TITLE
Post more decision information

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#415]
We need to be able to link decisions to their subject name usage without relying on stable ids in the sources. Primarily this happens by storing the rank, name & authorship so we rematch decisions when we update the dataset with a new import.

In the case of duplicates though this information is not enough!
We need to store more things like the status and/or parent to identify the exact record.

Decisions can hold this extra information as part of the [SimpleName class](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/model/SimpleName.java#L41) used for the subject:
 - `code` nomenclatural code to disambiguate inter kingdom homonym uninomials, e.g. lacking an authorship
 - `status`
 - `parent` the name of the direct parent in the classification or the accepted name in case of synonyms

The frontend does not post these attributes currently.
We need to discuss if we want them to be always posted or just selectively when we deal with duplicates or other special cases. Maybe this is also a manual decision?

If we always include all information this might lead to broken decisions not snapping to a name anymore in case they get placed under a different parent for example. But maybe that is a good thing?

**Comment by mdoering** [comment]
@yroskov @gdower this is crucial for your Scarabs test and before we enter a hell lot of decisions we should resolve this issue first!

**Comment by thomasstjerne** [comment]
The frontend will now post this information on the subject of the decision. 
I think that it should not be up to the user to choose whether to include these fields.

When a rematch is triggered by the user the backend could first see if a strict match is possible, if not try a match where the `parent` and `status` are not considered

**Comment by mdoering** [comment]
@gdower @yroskov please consider the implications of this!

If we want the matching to consider different levels of matching, then we'd need a user interface to do that and manage rematching in a more sophisticated way then just a simple button

**Comment by yroskov** [comment]
Let's touch this on our next call.

**Comment by yroskov** [comment]
For discussion. 
>Decisions can hold this extra information as part of the SimpleName class used for the subject:
For duplicated names: GSD ID & original nameID might be helpful.

**Comment by mdoering** [comment]
Posting decisions give a 400 error.
The posted decision.parent is a SimpleName object when it should just be the plain scientific name of the parent (direct parent from classification or accepted name in case of synonyms):

> `parent` the name of the direct parent in the classification or the accepted name in case of synonyms
