### ISSUE TITLE
more compact record view

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#43]
I prefer if you do not have to scroll. can we present details data in a more compact view?

**Comment by mdoering** [comment]
See [CoL](http://www.catalogueoflife.org/annual-checklist/2017/details/species/id/efca821f82c5d910bf35318a874bc6e0/common/c92b87ee6c010fba8bfbd5dc58764d1b) or [WoRMS](http://www.marinespecies.org/aphia.php?p=taxdetails&id=746019) pages for a much more compact view:

<img width="1028" alt="col ac" src="https://user-images.githubusercontent.com/327505/48807942-735c5480-ed1f-11e8-993f-ab9fee8640a8.png">

<img width="1113" alt="worms" src="https://user-images.githubusercontent.com/327505/48807987-96870400-ed1f-11e8-8439-3818e6075a79.png">

**Comment by mdoering** [comment]
A longer one from WoRMS: http://www.marinespecies.org/aphia.php?p=taxdetails&id=140605#sources

**Comment by mdoering** [comment]
Sorry to reopen, but I believe we still need to improve the taxon/name details page to become a lot more compact. Compare the current details to the one above in the old portal for the same species:

<img width="1623" alt="Screenshot 2019-05-09 at 18 33 12" src="https://user-images.githubusercontent.com/327505/57470451-22b6c480-7289-11e9-9184-5a6469a71ea1.png">

The taxon details also misses out some key data like the rank, publishedIn, name status which you can only find in the names page. We should also rethink this. There is not much benefit from showing the atomised name, homotypic and name index ids. But why not show all interesting name information already on the taxon page, maybe in dedicated "nomenclatural" section?

**Comment by mdoering** [comment]
What about these ideas for improvements:
 - remove all lines in the indented "subsections" synonyms and classification
 - increase size of the name itself as it should be the visual number one
 - show rank & status on first line after name in one row, e.g. `accepted species`
 - show publishedIn as 2nd information below name
 - render fossil and recent in one row with new label, e.g. `Presence: Fossil & Recent`
 - place origin last below classification

**Comment by thomasstjerne** [comment]
Moved to https://github.com/Sp2000/colplus-frontend/issues/199
