### ISSUE TITLE
missing menu items for released catalogues

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#434]
here is one: https://data.catalogue.life/dataset/2053

It seems there is no data. 
Is it because there is no import metric? we could create one as its a release.
But it might be good to check the dataset type and decide which menu items to show based on that.

CATALOGUES so far at least never have import metrics.

**Comment by mdoering** [comment]
see also #136 #431 #362

**Comment by thomasstjerne** [comment]
Duplicate of #407

**Comment by thomasstjerne** [comment]
It was because their datasetKey was < 1001 - I think thats how we used to distinguish the "special ones" from all the GSDs
