### ISSUE TITLE
Current catalogue always shown as last dataset in dataset search

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#471]
regardless of the page I am in `atest` always shows up last:

<img width="1683" alt="Screenshot 2019-12-27 at 07 43 33" src="https://user-images.githubusercontent.com/327505/71505180-9b9c7800-287c-11ea-8be6-92160bf9ce20.png">

<img width="1683" alt="Screenshot 2019-12-27 at 07 43 29" src="https://user-images.githubusercontent.com/327505/71505182-9b9c7800-287c-11ea-84a4-44b6a8de658d.png">

<img width="1683" alt="Screenshot 2019-12-27 at 07 43 25" src="https://user-images.githubusercontent.com/327505/71505183-9b9c7800-287c-11ea-8545-a081bf985403.png">

**Comment by thomasstjerne** [comment]
Pls reopen if this still happens
