### ISSUE TITLE
Allow creation of root taxa

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#472]
When creating a new managed dataset one cannot use the assembly tree as there is no root taxon. Allow to create new root taxa in the assembly menu if there is none or already existing ones.

<img width="1038" alt="Screenshot 2019-12-27 at 07 47 50" src="https://user-images.githubusercontent.com/327505/71505370-37c67f00-287d-11ea-8b0b-87534ae16dca.png">

**Comment by thomasstjerne** [comment]
Is it as simple as POSTING without parentId ?

**Comment by mdoering** [comment]
I would think so, yes

**Comment by thomasstjerne** [comment]
Would it be possible to bootstrap a new managed dataset with a "biota" root upon dataset creation? Maybe we can discuss at the call

**Comment by mdoering** [comment]
could do, yes.

**Comment by mdoering** [comment]
Can we add an option to create a new root taxon without a parent?
