### ISSUE TITLE
error when creating new sectors

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#473]
<img width="1434" alt="Screenshot 2019-12-27 at 07 52 26" src="https://user-images.githubusercontent.com/327505/71505558-eb2f7380-287d-11ea-84d1-1a3385149f1f.png">

**Comment by mdoering** [comment]
sectors are created after dragged from the source tree, but UI shows this error

**Comment by thomasstjerne** [comment]
Cannot reproduce, please reopen if this still aplly
