### ISSUE TITLE
How to switch catalogues?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#474]
It is unclear to me how one can switch catalogues.
Just visiting a URL like this still pulls up the draft number 3 in the UI:
https://data.dev.catalogue.life/catalogue/2050/assembly?assemblyTaxonKey=1

Should there not be a select somewhere?

**Comment by gdower** [comment]
We put that in the project-oriented frontend brainstorm: https://github.com/Sp2000/colplus-frontend/issues/465

**Comment by thomasstjerne** [comment]
The select is temporarily placed under "admin"

**Comment by thomasstjerne** [comment]
Under admin section: https://data.dev.catalogue.life/admin
![catalogueswitch](https://user-images.githubusercontent.com/1666484/75439281-cb89f980-5959-11ea-9ca2-7b749169a871.png)

It will be placed differently as part of #470
