### ISSUE TITLE
dataset sector link yields blank page

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#487]
Ff there is no sector the link shows a blank page:
https://data.catalogue.life/catalogue/3/dataset/2007/sectors

This also always happens if sectors exist if you paste the sector URL into the browser even if sectors:
https://data.catalogue.life/catalogue/3/dataset/1010/sectors

Also if its an exception we should never get blank pages but some error page. This is very irritating to people

**Comment by gdower** [comment]
@yroskov is also getting this bug on the dataset metadata page. The page goes blank when clicking the edit switch:

https://data.catalogue.life/catalogue/3/dataset/1206/meta
