### ISSUE TITLE
Wrong "The dataset is currently being imported." warning

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#494]
Why is there for all released datasets a warning?

> The dataset is currently being imported. Data may be inconsistent.

https://data.catalogue.life/catalogue/2079/dataset/2079/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic

**Comment by thomasstjerne** [comment]
Their latest state is processing :
https://api.catalogue.life/dataset/2079/import

If the latest state is not sth like finished, failed etc the frontend thinks its being imported

**Comment by mdoering** [comment]
oh, we seem to create the wrong state then for releases :)
