### ISSUE TITLE
Extend Sector form with ranks and entities

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#497]
A sector has been extended to cover 2 new list properties:

```
Set<Rank> ranks;
Set<EntityType> entities;
```

Both are optional configurations that allow to filter the copied data.

`rank` positively defines the included name usages by listing all ranks that should be copied, skipping all other ranks found (but still traversing into children). The frontend should allow to configure the selected ranks by providing some frequently used settings:
 - All (the default with ranks=NULL)
 - Linnean: major ranks only, i.e. kingdom, phylum, class, order, family, genus, species, subspecies
 - CoL: Linnean + superfamily, variety and form.

`entities`: the set of [taxon extension entities](http://api.catalogue.life/vocab/entitytype) that will be copied whenever a taxon is copied: vernacular names, distribution, description, media. Again the default NULL value means all

**Comment by thomasstjerne** [comment]
This is now deployed to dev, the PUT request go through fine, but on reload the `rank ` and/or `entities ` for the sector are missing.
