### ISSUE TITLE
show import button only for external datasets

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#501]
The import button in the import menu should only be shown for external datasets, not managed or uploaded (to be removed anyways)

https://data.catalogue.life/imports/finished?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed

<img width="1415" alt="Screenshot 2020-02-25 at 09 52 20" src="https://user-images.githubusercontent.com/327505/75230820-a6a85180-57b4-11ea-8bcb-d0915dc25e6f.png">

**Comment by mdoering** [comment]
releasing a managed dataset creates a new import metric. I think its good that these show up here too, but maybe they [should have a different state then `finished`](https://github.com/Sp2000/colplus-backend/issues/639) so they can easily be identified?

**Comment by thomasstjerne** [comment]
> releasing a managed dataset creates a new import metric. I think its good that these show up here too, but maybe they [should have a different state then `finished`](https://github.com/Sp2000/colplus-backend/issues/639) so they can easily be identified?

Agree. As long as the new state has `running: false` in the vocab api, it will end up in the finished section.
