### ISSUE TITLE
import attempts show the same data format from dataset

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#507]
When looking at various import attempts from a dataset that has changed its data format in between only the current format stored in the dataset object is shown. Take the format from the import instance instead.

<img width="1607" alt="Screenshot 2020-03-04 at 06 51 25" src="https://user-images.githubusercontent.com/327505/75814023-25b90d80-5de5-11ea-9055-316db1657b7c.png">

**Comment by thomasstjerne** [comment]
Could we add the format to the importer response? I would rather not "fish" for it in the verbatimByTermCount object.
https://api.catalogue.life/importer?limit=10&offset=0&state=unchanged&state=finished&state=released&state=canceled&state=failed

**Comment by mdoering** [comment]
oh, I will add format to the import object

**Comment by mdoering** [comment]
deployed to dev: https://api.dev.catalogue.life/importer?limit=10&offset=0&state=unchanged&state=finished&state=released&state=canceled&state=failed
