### ISSUE TITLE
dont show reference createdBy

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#509]
<img width="1775" alt="Screenshot 2020-03-04 at 22 09 07" src="https://user-images.githubusercontent.com/327505/75873875-d1ee0900-5e64-11ea-8796-2d27d97e9bc4.png">

can we show anything else for a reference?
The link/doi would be great! 

Parsed metadata?

**Comment by thomasstjerne** [comment]
> can we show anything else for a reference?
The link/doi would be great!

> Parsed metadata?

Can you point me towards example data where these exists?

**Comment by mdoering** [comment]
Its a potentially really big json csl document in the parsed bit. Bot sure how to best visualize this. I guess it needs to be generic.

Or we switch to BibTex as the parsed standard, the flexibility of CSL-JSON drives me nuts already

**Comment by mdoering** [comment]
here is a very simple example of only 2 fields parsed inside the CSL:
http://api.catalogue.life/dataset/3/reference/00008b76-6dc2-4600-879b-3e782a4816b2

```
{
  "created": "2020-01-07T02:07:26.995553",
  "createdBy": 103,
  "modified": "2020-01-07T02:07:26.995553",
  "modifiedBy": 103,
  "datasetKey": 3,
  "id": "00008b76-6dc2-4600-879b-3e782a4816b2",
  "sectorKey": 2729,
  "csl": {
    "author": [
      {
        "literal": "Copel."
      }
    ],
    "issued": {
      "date-parts": [
        [
          1906
        ]
      ]
    },
    "container-title": "In: Phil. Journ. Sci. 1, Suppl. IV: 252"
  },
  "citation": "Copel. In: Phil. Journ. Sci. 1, Suppl. IV: 252. (1906).",
  "year": 1906,
  "parsed": true
}
```
