### ISSUE TITLE
Verbatim data view

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#51]
Verbatim data is stored to represent a single source CSV record. Nearly all entities (taxon, name, synonym, vernacular, distribution, reference) have a foreign key to such a record. Interpreted entities sometimes are composed from several verbatim record, eg an infraspecific taxon in ACEF is primarily the infra epithet with a pointer to the species. 

How should that data be best shown?
On a single taxon page you habe many records to show (name, taxon, each vernacular, etc). maybe a link to open it elsewhere?

A dedicated verbatim viewer could also rather easily try to make the data linked so that all foreign keys are clickable.

**Comment by mdoering** [comment]
The verbatim data is a huge graph with a verbatim record being a node with lots of properties and relations to other records via only a few of their well known properties that are actually foreign keys.

All foreign key terms the Verbatim Data Viewer knows about can then be made a link to another verbatim record (VR) - linked data. As all VR have the same structure, basically a term/value map, the viewer should be rather simple.

Here a first shot of all foreign key terms that need to be linked:
(Syntax: RowTypeTerm . ForeignKeyPropertyTerm -> RowTypeTerm . PrimaryKeyPropertyTerm)

**ACEF**

Foreign Key | Primary Key
--- | ---
 AcceptedInfraSpecificTaxa.ParentSpeciesID | AcceptedSpecies.AcceptedTaxonID
 AcceptedInfraSpecificTaxa.ParentSpeciesID | AcceptedSpecies.AcceptedTaxonID
 Synonyms.AcceptedTaxonID | AcceptedSpecies/AcceptedInfraSpecificTaxa.AcceptedTaxonID
 Distribution.AcceptedTaxonID | AcceptedSpecies/AcceptedInfraSpecificTaxa.AcceptedTaxonID
 CommonNames.AcceptedTaxonID | AcceptedSpecies/AcceptedInfraSpecificTaxa.AcceptedTaxonID
 CommonNames.ReferenceID | Reference.ReferenceID
NameReferencesLinks.ID | AcceptedSpecies/AcceptedInfraSpecificTaxa.AcceptedTaxonID
NameReferencesLinks.ReferenceID | Reference.ReferenceID

**DwC**
Foreign Key | Primary Key
--- | ---
Taxon.parentNameUsageID | Taxon.taxonID
Taxon.acceptedNameUsageID | Taxon.taxonID
Taxon.originalNameUsageID | Taxon.taxonID
VernacularName.id | Taxon.taxonID
Description.id | Taxon.taxonID
Distribution.id | Taxon.taxonID
Multimedia.id | Taxon.taxonID
Reference.id | Taxon.taxonID
NameRelations.id | Taxon.taxonID
NameRelations.relatedNameUsageID | Taxon.taxonID

** ColDP **
Foreign Key | Primary Key
--- | ---
Taxon.nameID | Name.ID
Taxon.parentID | Taxon.ID
Taxon.referenceID | Reference.ID
Synonym.taxonID | Taxon.ID
Synonym.nameID | Name.ID
Name.publishedInID | Reference.ID
NameRel.nameID | Name.ID
NameRel.relatedNameID | Name.ID
NameRel.publishedInID | Reference.ID
Description.taxonID | Taxon.ID
Description.referenceID | Reference.ID
Media.taxonID | Taxon.ID
Distribution.taxonID | Taxon.ID
Distribution.referenceID | Reference.ID
VernacularName.taxonID | Taxon.ID
VernacularName.referenceID | Reference.ID

**Comment by mdoering** [comment]
A bit like Linked Data Browsers, e.g. DBPedia pages: http://dbpedia.org/page/Global_Biodiversity_Information_Facility

Alternatively the backend could know about the key links and decorate the verbatim records with API URL links for the respective keys?

**Comment by thomasstjerne** [comment]
And the terms will always be prefixed their format right?:
acef: dwc: or coldp:

**Comment by mdoering** [comment]
we have a Term interface also used in the GBIF API that defines that.
Each term has a namespace and a plain name which combined gives a full URL.
For the often rather long namespace we also define a unique short prefix that can be used instead. This is what we store for verbatim records. So example the Darwin Core term scientificName has:

```
simple name    = scientificName
namespace      = http://rs.tdwg.org/dwc/terms/
qualified name = http://rs.tdwg.org/dwc/terms/scientificName
NS prefix      = dwc
prefixed name  = dwc:scientificName
```

The relevant prefixes here are:
 - `acef` all terms in ACEF format
 - `col` all terms in ColDP format
 - `dwc` core terms for Darwin Core Archives
 - `dc` Dublin Core terms for Darwin Core Archives
 - `gbif` GBIF terms for Darwin Core Archives. Includes all extension rowTypes such as gbif:VernacularName
 - `cold` name relation terms for Darwin Core Archives (we should probably rather use coldwc here)

**Comment by mdoering** [comment]
I suggest to add an API method that takes a rowType and term parameters :

`/dataset/1234/verbatim?type=acef:AcceptedSpecies&term=acef:AcceptedTaxonID:k46521`

Arbitrary terms can then be given for filtering and be combined by providing multiple term parameters.
There is also already an additional `issue`parameter to filter by

**Comment by mdoering** [comment]
Example:
All verbatim records of the dataset:
http://api.col.plus/dataset/1709/verbatim

Just col:Name records:
http://api.col.plus/dataset/1709/verbatim?type=col:Name

**Comment by mdoering** [comment]
Deployed to dev: 
 - http://api-dev.col.plus/dataset/1709/verbatim?type=col:Name&term=col:ID:8
 - http://api-dev.col.plus/dataset/1027/verbatim?type=acef:AcceptedInfraSpecificTaxa&term=acef:AcceptedTaxonID:18-.02-.06-.00-.002-.002-.053-.c
 - http://api-dev.col.plus/dataset/1709/verbatim?type=col:Name&term=col:genus:Solanum

**Comment by thomasstjerne** [comment]
I realize now that I dont even need the foreign key mapping since all verbatim records (no matter type) will be showed on the same type of verbatim page.
So I only need the entire list of attribute names that links to other verbatim records and then render them as links

**Comment by thomasstjerne** [comment]
Seems it could boil down to this: https://github.com/Sp2000/colplus-frontend/blob/master/public/terms.json

Linking terms to their route entity in the ui

**Comment by mdoering** [comment]
see also #124

**Comment by mdoering** [comment]
No, the json links won't work.
They must resolve to a verbatim API call, not other entities. Its supposed to purely browse verbatim data - prime reason being that the interpreted view is often composed from several linked verbatim records

**Comment by mdoering** [comment]
The synonym on this page:
https://dev.col.plus/dataset/1140/name/fer-10-syn-12

... has a verbatimKey=108720

That gives the entry to the verbatim graph:
https://api-dev.col.plus/dataset/1140/verbatim/108720

From there one should be able to browse verbatim data and never leave the verbatim view.
So that synonym with acef:AcceptedTaxonID=fer-10 would have to link to
http://api-dev.col.plus/dataset/1140/verbatim?type=acef:AcceptedSpecies&type=acef:AcceptedInfraSpecificTaxa&term=acef:AcceptedTaxonID:fer-10

You need to know the type/term pair Synonym/AcceptedTaxonID is a link to AcceptedSpecies/AcceptedInfraSpecificTaxa.AcceptedTaxonID as in my table above

**Comment by mdoering** [comment]
Basically the main idea is being able ro navigate the graph according to the relational model of the underlying format. 

![Image](https://i.imgur.com/bWOlywO.jpg)

or ACEF:
![](http://www.catalogueoflife.org/sites/default/files/datafiles/ERD_Data%20Submission%20Format_29Sep2014.pdf)

**Comment by mdoering** [comment]
As the API returns lists I propose to only have "Verbatim" without an id as the section menu item and always render lists of verbatim records. We could even add an issue filter or others are the top at some point. Linking to interpreted entities/routes could also be done, but primarily the verbatim links should navigate you around the verbatim data.

**Comment by mdoering** [comment]
I have updated the verbatim API to treat term parameters in a simpler way.
Now you can just use the prefixed term as the parameter name and assign it a value. That now also allows to use colons in values safely:

http://api-dev.col.plus/dataset/1140/verbatim?type=acef:AcceptedSpecies&type=acef:AcceptedInfraSpecificTaxa&acef:AcceptedTaxonID=fer-10

**Comment by mdoering** [comment]
DwC datasets frequently do not have a dwc:taxonID term in the core but use dwca:ID instead.
The verbatim viewer should treat them the same and also link dwca:ID

Example Mammals of the world:
https://dev.col.plus/dataset/2014/taxon/10400073
