### ISSUE TITLE
Family name detail returns 404

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#53]
when coming from a search:
http://test.col.plus/dataset/1018/names?limit=50&offset=0&rank=family&reverse=true&sortBy=name

The details of "Adelidae" do show, but render a 404 for the verbatim record and its issues:
http://test.col.plus/dataset/1018/name/.5Y_R

When the details record is loaded directly the entire page gives a 404

**Comment by thomasstjerne** [comment]
Due to the dot in the param. This needs some server configuration

**Comment by thomasstjerne** [comment]
Duplicate of https://github.com/Sp2000/colplus-frontend/issues/82
