### ISSUE TITLE
Basic auth not using UTF8 for credentials

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#59]
I fail to login with a non ascii password, but it works using curl and the API directly.
The BASE64 Basic Authentication header is also different when using curl and the React app.

**Comment by thomasstjerne** [comment]
@mdoering can you check if this works now? I switched away from the build in auth config

**Comment by mdoering** [comment]
Afraid its still not working.
For a password with the German Umlaut `ö`I now get the following Authentication header (first 3 chars obscurred):

```
Authorization: Basic ***ya3VzOm32Z2xpY2g=
```

When I do the same from Java using UTF8 I get
```
Authorization: Basic ***ya3VzOm32Z2xpY2g=
```

... which surprisingly now also fails!
It seems the GBIF registry has been deployed with the new authentication fix that expects headers in UTF8, not in Latin1 anymore. When I do change the encoding used to send the header to GBIF from latin1 to UTF8 it all works!
