### ISSUE TITLE
Visualize assembly duplicates

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#63]
Finding, monitoring and acting on duplicate names in the CoL and its sources is probably the most important work when assembling the CoL and this needs the best tools to support.

Consider and document here how to best do that in the frontend.
We can broadly classify duplicates into:

1. [Duplicate names within the dataset](https://github.com/Sp2000/colplus-backend/issues/195)
2. [Duplicate names between the dataset and CoL](https://github.com/Sp2000/colplus-backend/issues/194)

For duplicates within a dataset we can use the search and limit results by datasetKey.

For duplicates between a dataset and the CoL we should be able to use the search and limit results by records in the draft catalogue only, i.e. datasetKey=3. This only catches records that are part of a mapped sector already and therefore have been copied to the draft. This should be the desired behavior, as we don't want to see all duplicates of WoRMS for example, just the part that is actually mapped to the CoL.

For each of those we typically want to filter by:
 - higher taxon: restrict results to group(s) within the tree. This is useful when evaluating a single or few sectors
 - rank: restrict results to user selected ranks
 - status: restrict results to user selected statuses
 - identical name with authorship, identical name without authorship, name variant (e.g. epithet gender): For this we should flag different issues (`duplicate name`, `???`, `potential variant`) to filter by

In general a [search result table](http://test.col.plus/dataset/1008/names?issue=duplicate%20name&limit=50&offset=100&reverse=false&status=accepted&status=provisionally%20accepted) ordered by name (to show duplicates next to each other), with a classification (see #60), the above filter options and the ability to batch apply a decision to multiple records should be covering the basic needs. When applying some of the above filters the corresponding duplicate record(s) might have been excluded (especially higher group & status). We need to think how to best include them in the shown table nevertheless.

Apart from a link from the issues tab *Duplicates* should probably be a tab in its own rights

**Comment by thomasstjerne** [comment]
Yuris workbench mockup:
![reports jpg](https://user-images.githubusercontent.com/1666484/52471357-01164600-2b91-11e9-858f-17e9a4ddcc75.jpeg)

**Comment by mdoering** [comment]
spreadsheet of different checks and the expected report columns can be found here:
https://docs.google.com/spreadsheets/d/1RIHaB1IdXy7WKSu_tL5V-M4YtGXDMKb9Cs3XxXieF7c/

**Comment by mdoering** [comment]
Backend API issue to drive most of this: https://github.com/Sp2000/colplus-backend/issues/254

I think there should be a dedicated page for duplicates.
And probably a summary view that queries all possible duplicate cases/checks and presents them just as counts per check or even just a boolean green/red which would be less of a backend burden?

**Comment by mdoering** [comment]
UI suggestions copied from email conversations:

**Expand details**
> being able to expand a single scientific name row within the duplicates table to get additional details on a name could be a useful feature (e.g., other issues the name is tagged with, possibly the parent name for synonyms). Essential report info like the full classification hierarchy should be displayed without having to expand a row.

**Guided workflow**
> Having a guided workflow interface with breadcrumbs (Step 1, Step 2, ..., Step n) would be a good usability enhancement even if it's just a simple page with set of links to follow ordered for optimal workflow efficiency (e.g., resolving the ACC-ACC and SYN-SYN duplicates first might simplify the editorial task of resolving ACC-SYN duplicates). I think Marcus is right that it might otherwise be hard to remember which combinations of filters have been used to address specific problems that frequently occur in datasets.

**Duplicate group sorting**
> In the first row for each duplicates group, it might also be useful to include a within group action menu that lets you select all, the oldest, newest, or record with the least info within a group rather than having to manually assess that for each group. That would be helpful for the first round of revisions when resolving groups with more than 2 duplicates.

**Columns to show**
> We provided these column views in the "Report Column" of the issues spreadsheet. Most of the columns are the same or are quite similar for duplicates issues, so if it's too hard to do a different view for different filter combinations then we could just use these columns for higher and lower rank duplicates:

> For species ranks and below:
`editorialDecision, datasetKey, id, parentId, sp2000StatusID, GSDNameStatus, genus, subgenus, specificEpithet, infraspecificMarker, infraspecificEpithet, authorship, rank, classificationHierarchy, parentScientificName`

> For higher ranks above species: 
`editorialDecision, datasetKey, id, parentId, sp2000StatusID, GSDNameStatus, uninomial, authorship, rank, classificationHierarchy, parentScientificName`
