### ISSUE TITLE
Classification tab using 100% CPU

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#80]
It might be due to a bug in the draft dataset but the [Classification menu uses 100% CPU for the StaphBase](http://test.col.plus/dataset/1204/classification) and causes Firefox to freeze. If allowed to run for a long time, eventually the genus Cretohister gets populated with a large number of families. Classification interface lag might be a problem when expanding taxa with large numbers of children.

**Comment by mdoering** [comment]
That sounds serious. Whatever the cause for large numbers of children, the UI should be able to work with hundred thousands of children in case datasets don't classify species properly
