### ISSUE TITLE
name with origin!=SOURCE shows 404s

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#82]
names and usages (taxa/synonyms) which have origin != SOURCE are created without a verbatimKey.
Issues and verbatim data is therefore not available and should not show as a 404 here:
http://test.col.plus/dataset/2000/name/.!Bjwe

**Comment by thomasstjerne** [comment]
Would it be possible not to have IDs starting with "." ?
This would fix it. 
The router expects the dot to indicate an extension (.html .jsp etc)

**Comment by mdoering** [comment]
yes, we can avoid the dot when we invent ids ourselves.
But if they come in as such we cannot I am afraid. Unlikely and rare for sure though.

**Comment by ayco-at-naturalis** [comment]
Would this affect the ES import? Provided Markus's solution that we just discussed can indeed be adopted

**Comment by ayco-at-naturalis** [comment]
(origin != SOURCE are created without a verbatimKey)

**Comment by thomasstjerne** [comment]
Please reopen if you encounter this again
