### ISSUE TITLE
Restyle name search

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#93]
The Name search results feel rather untidy. I suggest to follow the classic CoL search results more closely: http://www.catalogueoflife.org/col/search/all/key/scandens/fossil/1/match/1

That means in particular:
 - combine name & authorship
 - don't show issues (but leave the filter)
 - extend the status column to include the accepted name with a link in case of synonyms
 - avoid text wrapping
 - reduce classification. Needs discussion how to do that best. Just the kingdom/highest taxon? Also the lowest, e.g. family? Allow to toggle between full view of the entire classification and the short default version? Show the full classification under the name in a separate row similar to [GBIF](https://www.gbif.org/species/search?rank=SPECIES)?

**Comment by mdoering** [comment]
@yroskov any inputs appreciated

**Comment by thomasstjerne** [comment]
It would be ideal to have the entire formatted name in search result at some point, then we could simply render that rather than concatenating strings in a field

**Comment by yroskov** [comment]
Yes, please do search tool as close to CoL as possible. I need fields/columns: 
NameID (collapsible, i.e. visible on demand), 
Name (including authorstring; sorting rules: higher uninomial taxa go first; next binomials/trinomials with matching portions in genus name, then in species epithets, then in infraspecific epithets),
Rank,
Name Status (in the case of synonyms: ambiguous synonym for [accepted name with a link to species page],
Classification (full line with condensed presentation; ideally, collapsible to kingdom on demand),
Source Database.
Navigation in the list [it is not perfect in CoL]: condense space between lines; as much lines per page as possible; vertical and horizontal scrolling inside the page; option to jump from one page to another, ideally, including alphabet.

**Comment by mdoering** [comment]
yes, we wanted the formatted name in the API, sth we should do indeed: https://github.com/Sp2000/colplus-backend/issues/150
Maybe use the plain string for now until we have that?
